### ISSUE TITLE
Exercise 5-5: Add table description

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#10]
https://github.com/csci320/brosekerg/blob/5d7d8d3002ea02cc9329451134a9759b21908f75/exercise%205-5.txt#L1

Since you did not use `tee` to capture your create table statement, please add to this file the output of this command: `DESCRIBE student_major;`

That will allow me to see the full table definition.

**Comment by brosekerg** [comment]
Can I do this for all of the exercises I haven’t used the tee command on?

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by smattingly** [comment]
I don't know which things you did and did not use `tee` on. I need you to submit the requested information. If you did not, you will need to sort that out.

**Comment by smattingly** [comment]
5-5 now ok.

**Comment by brosekerg** [comment]
I responded to every issue fix so if u got everywhere I didnt tee we are good to go



Sent via the Samsung Galaxy S9, an AT&T 5G Evolution capable smartphone



-------- Original message --------
