### ISSUE TITLE
Exercise Set 2

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#11]
Although you merged and closed Pull Request #2, it contained my review comments on fixes you needed to make. Please see that PR for the details. I will use this Issue to track the status of all Set 2 fixes.

**Comment by brosekerg** [comment]
did u see where i implemented these fixes on this issue?

**Comment by smattingly** [comment]
These are not correct.
For 2-1, the statements you show, executed in that order, will not produce correct results. The problem is that it does change things, so I don't know what the contents of the table now are. Add the fact that this is now so old, and it's difficult for me to evaluate. If you will show me the results of `SELECT * FROM visit;`, and they are correct, I will accept that for 2-1.

For 2-3, you are asked to do (and capture) UPDATE statements. There are no UPDATE statements in the file that you submitted. You need to "show your work", not just the results.
