### ISSUE TITLE
Exercise set 19

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#21]
https://github.com/csci320/brosekerg/blob/2ecf49c284a9d5fe0c0e33a9afd2a161a70be1b1/E19/Exercise%20Set%2019#L1-L4

These are not correct. That is, the queries given are the ones we want, but you are asked to show how those queries could be injected by an attacker in the situation described. That requires the attacker to enter a string containing those queries, but some other things, too.

**Comment by brosekerg** [comment]
oh okay yeah i misunderstood i was writing queries as if they were the rest of the exercises meaning just looking up information. i will attempt to fix this

**Comment by brosekerg** [comment]
i updated this set, although im not confident its correct. used the sql injection tutorial for reference. let me know!

**Comment by smattingly** [comment]
You got the "harder" part right-- all the weird symbols that are needed to make the attack work. But for 2 and 3, your queries themselves have syntax errors (nothing to do with injection attack). You can try running just the queries (without all the extra injection attack symbols to find/fix the errors.

**Comment by brosekerg** [comment]
done

**Comment by smattingly** [comment]
👍
