### ISSUE TITLE
Exercise 25-1 (aggregation)

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#24]
https://github.com/csci320/brosekerg/blob/9c778f2f87fa119fbd911151d8a3306542ff0ec3/Exercise%20Set%2025#L34

The query should result in one document that says the count is 3.

If you are going to solve this with `aggregate()` you will need to `$group` by a made-up constant value to produce one result document. You might find it easier to use a different, special purpose aggregation function.

**Comment by brosekerg** [comment]
this is also fixed (code line 96)

**Comment by brosekerg** [comment]
both of these are now closed if you look at the other 25-1 post, right?

**Comment by smattingly** [comment]
👍
