### ISSUE TITLE
Exercise 24-2 and following

### ISSUE THREAD

**Issue by smattingly** [csci320/brosekerg#26]
https://github.com/csci320/brosekerg/blob/6d5b39e80346f4783f2b373326a964f9cd5d935d/Exercise%20Set%2024#L15

These inserts are not correct. There should be 14 visit documents. In each, the `student_id` value should refer back to a student document, but you have used more unique `student_id` values than there are student documents.

This affects all the remaining exercises in set 24 and maybe others beyond. This is the problem with not working steadily thru the semester.

**Comment by brosekerg** [comment]
i will go ahead and make the brand new table from scratch due to the _id and student_id field not matching up just right

**Comment by brosekerg** [comment]
set 24 is now completed

**Comment by smattingly** [comment]
Some of the data is still incorrect. Hannah should not have an empty visit array in the results. But it's close and the query syntax is correct, so we'll call it good.
